language: php

dist: xenial

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - CODECOVERAGE=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PREFER_LOWEST=1

    - php: 7.3
      env: CHECKS=1 DEFAULT=0

#    - php: 7.3
#      env: CODECOVERAGE=1 DEFAULT=0

before_install:
  - phpenv config-rm xdebug.ini

install:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi

script:
  - |
    if [[ $CODECOVERAGE == 1 ]]; then
      vendor/bin/phpunit --verbose --coverage-clover=clover.xml
    else
      vendor/bin/phpunit --verbose
    fi

  - if [[ $CHECKS == 1 ]]; then composer phpstan; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check; fi

after_success:
  - |
    if [[ $CODECOVERAGE == 1 ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      chmod +x php-coveralls.phar
      ./php-coveralls.phar
    fi

notifications:
  email: false